[project]
name = "polars-inspector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "black>=25.1.0",
    "ipykernel>=6.29.5",
    "polars>=1.21.0",
    "ruff>=0.9.5",
]
